# -*- coding: utf-8 -*-
"""DistributoreAutomatico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dU_Qj3QyOmXTGRlEo22uq0v-urJruxh

#Un distributore automatico della scuola registra quante merendine vengono vendute ogni ora.

Scrivi un programma in Python che:

Chiede all’utente di inserire il numero di merendine vendute ogni ora, per 5 ore consecutive (es. dalle 8 alle 13).

controllare che ogni valore inserito sia positivo o zero.
Salva i dati in una lista.
___


##Definisci e usa tre funzioni:


Che restituisce la somma totale delle vendite.

che restituisce l’indice dell’ora in cui sono state vendute più merendine.

che restituisce quante ore hanno avuto vendite minori della soglia.
___

##Nel programma principale:

stampa la lista delle vendite,

stampa il totale delle vendite,

stampa l’ora con più vendite (es: “ora 3”, non l’indice),

chiede all’utente una soglia e stampa quante ore sono sotto soglia.
"""

def somma_vendite(lista):
  somma = 0
  for i in range(len(lista)):
    somma += int(lista[i])
  return somma

def ora_max(lista):
  max = 0
  ora = 0
  for i in range(len(lista)):
    if int(lista[i]) > max:
      max = int(lista[i])
      ora = i
  return ora + 1

def under_soglia(lista, soglia):
  ore_under = 0
  for i in range(len(lista)):
    if int(lista[i]) < int(soglia):
      ore_under+=1
  return ore_under

vendite = []
n = 0
print("Inserisci il numero di merendine vendute ad ogni ora: ")
for i in range(5):
  print("Ora ", i + 1)
  n = input("Vendite: ")
  while int(n) < 0:
    print("valore invalido, reinseriscilo.")
    print("Ora ", i + 1)
    n = input("Vendite: ")
  vendite.append(n)
soglia = input("Inserisci una soglia di vendite da superare: ")

print("\n")
print("Vendite: ", vendite)
print("Somma delle vendite: ", somma_vendite(vendite))
print("L'ora che ha venduto di più è stata l'ora ", ora_max(vendite))
print("Le ore che hanno venduto sotto la soglia sono: ", under_soglia(vendite, soglia))

